export const COMPETITION_STATUS_CREATED = 'COMPETITION_STATUS_CREATED'
export const COMPETITION_STATUS_STARTED = 'COMPETITION_STATUS_STARTED'
export const COMPETITION_STATUS_FINISHED = 'COMPETITION_STATUS_FINISHED'
export const COMPETITION_STATUS_PUBLISHED = 'COMPETITION_STATUS_PUBLISHED'