const COMPETITION_STATUSES = {
    created: 'COMPETITION_STATUS_CREATED',
    started: 'COMPETITION_STATUS_STARTED',
    finished: 'COMPETITION_STATUS_FINISHED',
    published: 'COMPETITION_STATUS_PUBLISHED'
}

module.exports = COMPETITION_STATUSES